version: "2.1"
services:

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - /srv/dev-disk-by-label-Diskb/mainshare/config/sonarr:/config
      - /srv/dev-disk-by-label-Diskb/mainshare/media/TVShows:/tv
      - /srv/dev-disk-by-label-Diskb/mainshare/download/complete:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
