version: "2.1"
services:

  vpn:
    image: bubuntux/nordvpn
    network_mode: bridge
    container_name: vpn
    cap_add:
      - NET_ADMIN               # Required
      - SYS_MODULE              # Required for TECHNOLOGY=NordLynx
    devices:
      - /dev/net/tun            # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=user@email.com     # Required
      - PASS='pas$word'         # Dont even try using this
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx 
      - NETWORK=192.168.2.0/24
    ports:
      - 8112:8112 

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    #network_mode: host
    network_mode: service:vpn
    depends_on:
      - vpn
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/London
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /srv/dev-disk-by-label-Diskb/mainshare/config/deluge:/config
      - /srv/dev-disk-by-label-Diskb/mainshare/download:/downloads
<<<<<<< HEAD
    #ports:
    #  - 8112:8112
=======
  #  ports:
  #    - 8112:8112
>>>>>>> 6cac7f515bcd75f9985cae4b1281ddc40129f7f6
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Pacific/Auckland
      - UMASK_SET=022 #optional
    volumes:
      - /srv/dev-disk-by-label-Diskb/mainshare/config/sonarr:/config
      - /srv/dev-disk-by-label-Diskb/mainshare/media/TVShows:/tv
      - /srv/dev-disk-by-label-Diskb/mainshare/download:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Pacific/Auckland
      - UMASK_SET=022 #optional
    volumes:
      - /srv/dev-disk-by-label-Diskb/mainshare/config/radarr:/config
      - /srv/dev-disk-by-label-Diskb/mainshare/media/movies:/movies
      - /srv/dev-disk-by-label-Diskb/mainshare/download/complete:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Pacific/Auckland
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=run options here #optional
    volumes:
      - /srv/dev-disk-by-label-Diskb/mainshare/config/jackett:/config

    ports:
      - 9117:9117
    restart: unless-stopped



