version: "2.1"
services:
  unifi-controller:
    image: linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024M #optional
      - TZ=Pacific/Auckland
    volumes:
      - /srv/dev-disk-by-label-Diskb/mainshare/config/unifi:/config
    ports:
      - 3478:3478/udp
      #- 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514 #optional
    restart: unless-stopped

  unifi-video:
    image: pducharme/unifi-video-controller
    container_name: unifi-video
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024M #optional
      - CREATE_TMPFS=no
      - DEBUG=1 
      - TZ=Pacific/Auckland
    cap_add:
      - DAC_READ_SEARCH   
    ports:      
      - 10001:10001 
      - 1935:1935 
      - 6666:6666 
      - 7080:7080 
      - 7442:7442 
      - 7443:7443 
      - 7444:7444 
      - 7445:7445 
      - 7446:7446 
      - 7447:7447 
    volumes:
      - /srv/dev-disk-by-label-Diskb/mainshare/unifi-video:/var/lib/unifi-video
      - /srv/dev-disk-by-label-Diskb/mainshare/unifi-video/videos:/var/lib/unifi-video/videos
    tmpfs:                                                                                   
      - /var/cache/unifi-video                                                                               
