version: "2.1"
services:
  vpn:
    container_name: nordvpn
    image: bubuntux/nordvpn
    cap_add:
      - NET_ADMIN               # Required
      - SYS_MODULE              # Required for TECHNOLOGY=NordLynx
    devices:
      - /dev/net/tun            # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=     # Required
      - PASS=         # Required
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx

  torrent:
    container_name: deluge
    image: linuxserver/deluge
    container_name: deluge
    network_mode: service:vpn
    depends_on:
      - vpn
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/London
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /srv/dev-disk-by-label-Diskb/mainshare/config/deluge:/config
      - /srv/dev-disk-by-label-Diskb/mainshare/download:/downloads
    #ports:
    #  - 8112:8112
    restart: unless-stopped


  web:
    container_name: deluge_proxy
    image: dperson/nginx        # https://github.com/dperson/nginx
    links:                                                                                   
      - vpn:torrent                                                                          
    depends_on:                                                                              
      - torrent                                                                              
    tmpfs:                                                                                   
      - /run                                                                                 
      - /tmp                                                                                 
      - /var/cache/nginx                                                                    
    ports:                                                                                   
      - 8113:80                                                                                
    

                                                                          
    command: -w "http://torrent:8112/;/" 

# The torrent service would be available at http://localhost:8113/ 