version: "2.1"
services:
  vpn:
    image: bubuntux/nordvpn
    cap_add:
      - NET_ADMIN               # Required
      - SYS_MODULE              # Required for TECHNOLOGY=NordLynx
    devices:
      - /dev/net/tun            # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=user@email.com     # Required
      - PASS='pas$word'         # Required
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx


   torrent:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: service:vpn
    depends_on:
      - vpn

    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/London
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /srv/dev-disk-by-label-Diskb/mainshare/config/deluge:/config
      - /srv/dev-disk-by-label-Diskb/mainshare/download:/downloads
    #ports:
    #  - 8112:8112
    restart: unless-stopped


  web:
    image: dperson/nginx        # https://github.com/dperson/nginx
    links:                                                                                   
      - vpn:torrent                                                                          
    depends_on:                                                                              
      - torrent                                                                              
    tmpfs:                                                                                   
      - /run                                                                                 
      - /tmp                                                                                 
      - /var/cache/nginx                                                                     
    ports:                                                                                   
      - 80:80                                                                                
      - 443:443  
      - 8112:8112    

                                                                          
    command: -w "http://torrent:8080/;/" 

# The torrent service would be available at http://localhost/ 