version: "2.1"
services:
  torrent:
    container_name: deluge
    image: linuxserver/deluge
    environment:
      - PUID=1000
      - PGID=100
      - TZ=TZ=Pacific/Auckland
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /srv/dev-disk-by-label-Diskb/mainshare/config/deluge:/config
      - /srv/dev-disk-by-label-Diskb/mainshare/download:/downloads
    ports:
      - 8112:8112
    labels:
      - traefik.enable=true
      - traefik.http.routers.deluge.rule=Host(`deluge.local`)
      - traefik.http.services.deluge.loadbalancer.server.port=8112 
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Pacific/Auckland
      - UMASK_SET=022 #optional
    volumes:
      - /srv/dev-disk-by-label-Diskb/mainshare/config/sonarr:/config
      - /srv/dev-disk-by-label-Diskb/mainshare/media/TVShows:/tv
      - /srv/dev-disk-by-label-Diskb/mainshare/download:/downloads
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.rule=Host(`sonarr.local`)
    #ports:
    #  - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Pacific/Auckland
      - UMASK_SET=022 #optional
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.rule=Host(`radarr.local`)
    volumes:
      - /srv/dev-disk-by-label-Diskb/mainshare/config/radarr:/config
      - /srv/dev-disk-by-label-Diskb/mainshare/media/movies:/movies
      - /srv/dev-disk-by-label-Diskb/mainshare/download/complete:/downloads
    #ports:
    #  - 7878:7878
    restart: unless-stopped
    
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Pacific/Auckland
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=run options here #optional
    labels:
      - traefik.enable=true
      - traefik.http.routers.jackett.rule=Host(`jackett.local`)
    volumes:
      - /srv/dev-disk-by-label-Diskb/mainshare/config/jackett:/config

    #ports:
    #  - 9117:9117
    restart: unless-stopped

  webgrabplus:
    image: linuxserver/webgrabplus
    container_name: webgrabplus
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - /srv/dev-disk-by-label-Diskb/mainshare/config/webgrabplus:/config
      - /srv/dev-disk-by-label-Diskb/mainshare/webgrabplus:/data
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    #network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    ports:
      - 32400:32400
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.local`)"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
    volumes:
      - /srv/dev-disk-by-label-Diskb/mainshare/config/plex:/config
      - /srv/dev-disk-by-label-Diskb/mainshare/media/movies:/movies
      - /srv/dev-disk-by-label-Diskb/mainshare/media/TVShows:/tv
    restart: unless-stopped