version: "2.1"
services:
  reverse-proxy:
    image: traefik
    container_name: traefik
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    command:
      - --api.insecure=true
      - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --serversTransport.insecureSkipVerify=true
      - --entryPoints.web.address=:80 
      - --entryPoints.websecure.address=:443
    ports:
      - "80:80"
      - "8081:8080"
      - 443:443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped