version: "2.1"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    volumes:
      - /srv/dev-disk-by-label-Diskb/mainshare/config/plex:/config
      - /srv/dev-disk-by-label-Diskb/mainshare/media/movies:/movies
      - /srv/dev-disk-by-label-Diskb/mainshare/media/TVShows:/tv
    restart: unless-stopped