version: "2.1"
services:
  filebrowser:
    image:  filebrowser/filebrowser
    container_name: filebrowser
    ports:
      - 80:80
    environment:
      - PUID=1000 #optional
      - PGID=100 #optional
      - TZ=Pacific/Auckland
    volumes:
      - /srv/dev-disk-by-label-Diskb/mainshare:/srv
      - /srv/dev-disk-by-label-Diskb/mainshare/config/filebrowser/database.db:/database.db
      - /srv/dev-disk-by-label-Diskb/mainshare/config/filebrowser/.filebrowser.json:/.filebrowser.json
    restart: unless-stopped

