
version: "2"
services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Pacific/Auckland
    volumes:
      - /srv/dev-disk-by-label-Diskb/mainshare/config/nextcloud:/config
      - /srv/dev-disk-by-label-Diskb/mainshare/nextcloud:/data
    #ports:
    #  - 443:443
    #  - 80:80
    depends_on:
      - mariadb
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.tls=true
      - traefik.http.routers.nextcloud.rule=Host(`cloud.stanners.co.nz`)
      - traefik.http.routers.nextcloud.entrypoints=websecure
      - traefik.http.routers.nextcloud.middlewares=nextcloud-redirect
      
      - traefik.http.services.nextcloud.loadbalancer.server.port=443 
      #- traefik.http.services.nextcloud.loadbalancer.server.port=80
      - traefik.http.services.nextcloud.loadbalancer.server.scheme=https   
      
      - traefik.http.middlewares.nextcloud-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.nextcloud-redirect.redirectscheme.permanent=true

       
 


    restart: unless-stopped

  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=100
      - MYSQL_ROOT_PASSWORD=lenovo63
      - TZ=Pacific/Auckland
    volumes:
      - /srv/dev-disk-by-label-Diskb/mainshare/config/mariadb:/config
    restart: unless-stopped

