version: "2.1"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - TZ=Europe/Paris
      - PLEX_CLAIM=claim-xxxxxxxxxxxxxx
      - PLEX_UID=${USER}
      - PLEX_GID=${USER}
      - VERSION=docker
    volumes:
      - /srv/dev-disk-by-label-Diskb/mainshare/config/plex:/config
      - /srv/dev-disk-by-label-Diskb/mainshare/media/movies:/movies
      - /srv/dev-disk-by-label-Diskb/mainshare/media/TVShows:/tv
    hostname: plex.local
    ports:
     - 32400:32400/tcp
     - 32400:32400/udp
     - 3005:3005/tcp
     - 8324:8324/tcp
     - 32469:32469/tcp
     - 1900:1900/udp
     - 32410:32410/udp
     - 32412:32412/udp
     - 32413:32413/udp
     - 32414:32414/udp
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.local`)"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"